on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: A job to do tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test step
        uses: ./ # Uses an action in the root directory
        id: alpine-ci
        with:
          host: 'host'
          user: 'user'
      - name: Get the output
        run: echo "The output is ${{ steps.alpine-ci.outputs.error }}"
